# Generated by Django 4.1.1 on 2022-09-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_subscribedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
