# Generated by Django 4.1.1 on 2022-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(default='hell', upload_to=''),
            preserve_default=False,
        ),
    ]
