# Generated by Django 4.1.1 on 2022-09-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_testimonial_client_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('financial', 'Financial Consultancy'), ('strategy', 'Strategy Consultancy'), ('tax', 'Tax Consultancy')], max_length=9)),
                ('comment', models.TextField()),
            ],
        ),
    ]
