# Generated by Django 4.1.1 on 2022-09-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquote',
            name='service',
            field=models.CharField(choices=[('financial', 'Financial Consultancy'), ('strategy', 'Strategy Consultancy'), ('tax', 'Tax Consultancy')], default='financial', max_length=9),
        ),
    ]
